name: Backend CI

on:
  push:
    branches:
      - main
    paths:
      - 'quizzAPPback/**'
  pull_request:
    branches:
      - main
    paths:
      - 'quizzAPPback/**'

jobs:
  backend:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: quizzapp
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Navigate to quizzAPPback directory
        run: cd quizzAPPback

      - name: Build and test with Maven
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/quizzapp?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: root
          SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
          SPRING_JPA_SHOW_SQL: true
        run: |
          cd quizzAPPback
          mvn clean test

      - name: Upload backend test results
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-results
          path: quizzAPPback/target/surefire-reports/
