name: Frontend CI

on:
  push:
    branches:
      - main
    paths:
      - 'quizzAPPfront/**'
  pull_request:
    branches:
      - main
    paths:
      - 'quizzAPPfront/**'

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Navigate to quizzAPPfront directory
        run: cd quizzAPPfront

      - name: Install dependencies
        run: |
          cd quizzAPPfront
          npm ci

      - name: Run tests
        run: |
          cd quizzAPPfront
          npm test -- --coverage --ci

      - name: Upload frontend coverage
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: quizzAPPfront/coverage/
